import Head from 'next/head'
import Table from '../components/Table/Table'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Table/>
    </>
  )
}
